server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: simulador-fdco
  
  profiles:
    active: development
    
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m
      
  jackson:
    time-zone: America/Sao_Paulo
    locale: pt_BR
    date-format: yyyy-MM-dd HH:mm:ss
    
  mvc:
    throw-exception-if-no-handler-found: true
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    br.gov.sudeco: INFO
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"